import turtle as t
import time

h = input('Your name (Child): ')
sc = t.Screen()
sc.setup(width=1.0, height=1.0)
sc.bgcolor('#050301')
sc.title("Happy Mother's Day!")
s = t.Turtle()
s.hideturtle()
t.hideturtle()
s.penup()
s.goto(-750, 375)
s.pd()
s.color('#ffd6a5')
s.write('Greetings!', font=('Times New Roman', 20, 'italic'))
t.speed(2)
t.color('#ffadad')
t.pensize(15)
t.penup()
t.goto(-100, 100)
t.pendown()
t.circle(60)
t.penup()
t.right(90)
t.forward(20)
t.pendown()
t.left(90)
t.forward(100)
t.right(60)
t.forward(250)
t.right(90)
t.forward(45)
t.right(90)
t.forward(200)
t.left(160)
t.forward(250)
t.right(100)
t.forward(225)
t.right(100)
t.forward(250)
t.left(160)
t.forward(200)
t.right(90)
t.forward(45)
t.right(90)
t.forward(250)
t.right(60)
t.forward(100)
t.penup()
t.goto(150, 200)
t.color('#a39fe1')
t.pendown()
t.write('Happy', align='center', font=("Times New Roman", 30, 'italic'))
t.penup()
t.goto(150, 140)
t.color('#fec6df')
t.pendown()
t.write("Mother's", align='center', font=('Times New Roman', 45, 'italic'))
t.penup()
t.goto(150, 100)
t.color('#feecd6')
t.pendown()
t.write('Day!', align='center', font=('Times New Roman', 30, 'italic'))
t.penup()
t.goto(235, -154)
t.pendown()
t.color('lightblue')
t.write('May 12, Sunday ', align='center', font=('Arial Rounded MT Bold', 15, 'bold'))
t.color('violet')
t.speed(10)
t.penup()
t.pensize(3)
t.goto(156, 34)
t.pendown()
for i in range(36):
    t.forward(75)
    t.left(165)
t.color('cyan')
t.penup()
t.pensize(3)
t.goto(165, 0)
t.pendown()
for i in range(36):
    t.forward(75)
    t.left(165)
t.color('violet')
t.penup()
t.pensize(3)
t.goto(178, -34)
t.pendown()
for i in range(36):
    t.forward(35)
    t.left(165)
t.penup()
t.goto(-293, 272)
t.color('#f8d8e4')
t.pendown()
t.pensize(5)
t.speed(2)
t.rt(45)
t.fd(20)
t.lt(45)
t.fd(30)
t.lt(45)
t.fd(20)
t.lt(45)
t.fd(20)
t.lt(45)
t.fd(80)
t.lt(90)
t.fd(80)
t.lt(45)
t.fd(20)
t.lt(45)
t.fd(20)
t.lt(45)
t.fd(30)
t.lt(45)
t.fd(20)
time.sleep(5)
t.clear()
s.clear()
s.pendown()
s.write('My Message', font=('Times New Roman', 20, 'italic'))
t.penup()
t.goto(0, 240)
t.color('#e5f0fa')
t.pendown()
t.write('Happy', align='center', font=('Times New Roman', 45, 'normal'))
t.penup()
t.goto(0, 160)
t.color('#bde0fe')
t.pendown()
t.write("Mother's", align='center', font=('Times New Roman', 60, 'normal'))
t.penup()
t.goto(0, 90)
t.color('#8fc9ff')
t.pendown()
t.write('Day!', align='center', font=('Times New Roman', 45, 'normal'))
t.penup()
t.goto(-192, 180)
t.pendown()
t.pensize(5)
t.color('#9bf6ff')
t.settiltangle(90)
for i in range(5):
    t.fd(100)
    t.lt(144)
t.penup()
t.goto(240, 180)
t.pendown()
t.color('#9bf6ff')
t.settiltangle(90)
for i in range(5):
    t.fd(100)
    t.lt(144)
t.penup()
t.goto(0, 0)
t.pendown()
t.color('violet')
t.write('Amma, you are the one who cut this rock into a glistening diamond. Every second beat of my heart is yours.',align='center', font=('Arial Rounded MT Bold', 10,'bold'))
t.penup()
t.goto(0, -13)
t.right(1440)
t.pendown()
t.write("You are an astounding cook, singer, teacher, and best of all.......Mother! Your skills are the one of the reasons you would be the one flower I'd've picked if all mothers were flowers!",
    align='center', font=('Arial Rounded MT Bold',10, 'bold'))
t.penup()
t.goto(0, -27)
t.right(1440)
t.pendown()
t.write("Your behaviour is polite, gentle and kind. I'm proud of you!", align='center', font=('Arial Rounded MT Bold',10, 'bold'))
t.penup()
t.goto(0, -41)
t.right(1440)
t.pendown()
t.write('Yours lovingly,',  align='center', font=('Arial Rounded MT Bold',10, 'bold'))
t.penup()
t.goto(0, -55)
t.right(1440)
t.pendown()
t.write('Your son, friend and student,', align='center', font=('Arial Rounded MT Bold',10, 'bold'))
t.penup()
t.goto(0, -69)
t.right(1440)
t.pendown()
t.write(h,  align='center', font=('Arial Rounded MT Bold',10, 'bold'))
t.color('#caffbf')
t.penup()
t.goto(0, -152)
t.begin_fill()
t.pendown()
t.rt(90)
t.fd(40)
t.lt(45)
t.fd(60)
t.lt(45)
t.fd(40)
t.lt(45)
t.fd(40)
t.lt(45)
t.fd(160)
t.lt(90)
t.fd(160)
t.lt(45)
t.fd(40)
t.lt(45)
t.fd(40)
t.lt(45)
t.fd(60)
t.lt(45)
t.fd(40)
t.penup()
t.goto(-192, -192)
t.rt(45)
t.pendown()
t.rt(180)
t.fd(40)
t.bk(20)
t.rt(90)
t.fd(60)
t.lt(90)
t.fd(20)
t.bk(40)
t.penup()
t.goto(150, -192)
t.pendown()
t.rt(45)
t.fd(50)
t.lt(90)
t.fd(50)
t.bk(50)
t.lt(225)
t.fd(30)
t.penup()
t.goto(222, -222)
t.pendown()
t.circle(30)
t.penup()
t.goto(302, -192)
t.pendown()
t.fd(55)
t.lt(45)
t.fd(5 * (2 ** 0.5))
t.lt(45)
t.fd(30)
t.lt(45)
t.fd(5 * (2 ** 0.5))
t.lt(45)
t.fd(55)
t.penup()
t.goto(-252,-222)
t.pendown()
t.circle(60)
t.penup()
t.goto(-342, -192)
t.pendown()
t.fd(1)
t.penup()
t.goto(-282, -192)
t.pendown()
t.bk(1)
t.penup()
t.goto(-342, -222)
t.right(180)
t.pendown()
t.circle(30, 180)
time.sleep(5)
t.clear()
s.clear()
s.write('Your Family', font=('Times New Roman', 20, 'italic'))
t.penup()
t.goto(0, 150)
t.pendown()
t.color('#f1e7eb')
t.write('Amma'+ ',', align='center', font=('Times New Roman', 50, 'italic'))
t.penup()
t.goto(0, 100)
t.right(1440)
t.pendown()
t.color('#f8d8e4')
t.write('You, on behalf of our family', align='center', font=('Times New Roman', 20, 'italic'))
t.penup()
t.goto(0, 60)
t.right(1440)
t.pendown()
t.color('#ffc8dd')
t.write('are:' ,align='center', font=('Times New Roman', 20, 'italic'))
t.penup()
t.goto(0, 20)
t.right(1440)
t.pendown()
t.color('#ffadcb')
t.write('an awesome mother, sister, daughter, cousin, niece, wife, sister in law, daughter in law, aunt, teacher, cook,  singer, and focused learner, and a kind, gentle, polite, amusing, amicable, confelicit, and amazing person!', align='center', font=('Baskerville', 12, 'italic'))
t.penup()
t.goto(0, -40)
t.lt(135)
t.pendown()
t.color('#c7aff7')
t.rt(90)
t.fd(40)
t.lt(45)
t.fd(60)
t.lt(45)
t.fd(40)
t.lt(45)
t.fd(40)
t.lt(45)
t.fd(160)
t.lt(90)
t.fd(160)
t.lt(45)
t.fd(40)
t.lt(45)
t.fd(40)
t.lt(45)
t.fd(60)
t.lt(45)
t.fd(40)
t.penup()
t.goto(-300, -20)
t.rt(135)
t.pendown()
t.bk(200)
t.fd(200)
t.right(135)
t.fd(100)
t.lt(90)
t.fd(100)
t.rt(135)
t.fd(200)
t.penup()
t.goto(170, -20)
t.pendown()
t.rt(180)
t.bk(200)
t.fd(200)
t.right(135)
t.fd(100)
t.lt(90)
t.fd(100)
t.rt(135)
t.fd(200)
t.mainloop()